sudo: required

services:
    docker

before_install:
    - docker build -t kiranvits/react-client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kiranvits/react-client-test npm test -- --coverage

after_success:
    - docker build -t kiranvits/multi-client ./client
    - docker build -t kiranvits/multi-worker ./worker
    - docker build -t kiranvits/multi-server ./server
    - docker build -t kiranvits/multi-nginx ./nginx
    # Login to Docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images to Docker hub
    - docker push kiranvits/multi-client
    - docker push kiranvits/multi-worker
    - docker push kiranvits/multi-server
    - docker push kiranvits/multi-nginx

